import Head from "next/head";
import Script from "next/script";
import tw from "tailwind-styled-components";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Card from "../components/card";
import { nftData } from "./../components/data";
import Link from "next/link";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Redbrick Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet"></link>
        {/* no output file, check https://nextjs.org/docs/messages/no-css-tags */}
      </Head>

      <Header />
      <div className="ml-60">
        <div className="flex">
          <div className="ml-20 pt-20 text-start text-white lg:w-1/2">
            <h1 className="text-7xl font-semibold leading-normal">
              Hey Redbrickers, thank you for your dedication!
            </h1>
            <p className="font-light text-gray-200 mt-3 pr-40 ">
              We appreciate everything that you do, and as a way of saying thank
              you we wanted to offer you something unique... just like the work
              you do at Redbrick! Please select the anniversary year that you
              are celebrating below to claim your NFT.
            </p>
          </div>
        </div>
        <div className="flex gap-10 place-items-center mt-10 ml-20">
          {nftData.map((item) => (
            <Card key={item.id} {...item} />
          ))}
        </div>
      </div>
      <Footer />
    </Container>
  );
}

const Container = tw.div`
w-full
h-screen
text-white
justify-center
px-7
`;
