import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import tw from "tailwind-styled-components"
import Header from '../components/Header'
import Main from '../components/Main'
import Footer from '../components/Footer'

const Container = tw.div`
w-screen
h-screen
text-white
justify-center
px-7
`

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Redbrick Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script id="tailwind" src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp" />

      <script>
              tailwind.config = {
                
              }
      </script>

      <Header />

      <Main />

      <Footer />

    </Container>
  )
}